from docx import Document
from docx.shared import Inches, Pt
from pathlib import Path

OUT=Path('communication_redo'); OUT.mkdir(exist_ok=True)
refs = [
"Blitzstein, J. K., & Hwang, J. (2019). Introduction to Probability (2nd ed.). Chapman and Hall/CRC.",
"Mitsokapas, E., Schäfer, B., Harris, R. J., & Beck, C. (2021). Statistical characterization of airplane delays. Scientific Reports, 11, 7855. https://doi.org/10.1038/s41598-021-87279-8",
"Mueller, E. R., & Chatterji, G. B. (2002). Analysis of aircraft arrival and departure delay characteristics. AIAA Aircraft Technology, Integration, and Operations Technical Forum, AIAA 2002-5866. https://doi.org/10.2514/6.2002-5866"
]
def base(title):
 d=Document(); sec=d.sections[0]; sec.top_margin=Inches(.75); sec.bottom_margin=Inches(.75)
 p=d.add_paragraph(title, style='Title'); p.runs[0].font.color.rgb=None
 return d
def h(d,t): d.add_heading(t, level=1)
def p(d,t): d.add_paragraph(t)
def references(d):
 h(d,'References')
 for x in refs: d.add_paragraph(x)

d=base('Literature Review Discrete Probability Distributions')
p(d,'This review states the distributional theory used in the flight-delay analysis and identifies the domain of each moment-generating function. The standard formulas and conditions follow Blitzstein and Hwang (2019).')
items=[
('Poisson','X ~ Poisson(lambda) models a count in a fixed interval. E[X] = Var(X) = lambda. M_X(t) = exp{lambda(exp(t) - 1)}, defined for every real t. The model assumes a stable rate and independent events. Daily flight delays may violate these assumptions through weather, congestion, and propagation.'),
('Binomial','X ~ Binomial(n, p) counts successes in n Bernoulli trials. E[X] = np and Var(X) = np(1-p). M_X(t) = (1-p+p exp(t))^n, defined for every real t. It requires fixed n, binary outcomes, common p, and independence.'),
('Geometric','Under the trials-until-first-success convention, P(X=x)=(1-p)^(x-1)p for x=1,2,... . E[X]=1/p and Var(X)=(1-p)/p^2. M_X(t)=p exp(t)/[1-(1-p)exp(t)], defined for t < -log(1-p). It requires independent trials with common p and has the memoryless property.'),
('Negative Binomial','For trials until r successes, E[X]=r/p and Var(X)=r(1-p)/p^2. M_X(t)=[p exp(t)/{1-(1-p)exp(t)}]^r, defined for t < -log(1-p). The Geometric distribution is the r=1 case.'),
('Hypergeometric','X ~ Hypergeometric(N,K,n) counts successes in n selections without replacement. E[X]=nK/N and Var(X)=n(K/N)(1-K/N)(N-n)/(N-1). Its MGF is the finite support sum M_X(t)=sum_x exp(tx)P(X=x), defined for every real t. The changing success probability distinguishes it from the Binomial model.')]
for a,b in items: h(d,a); p(d,b)
h(d,'Connection to Flight Delays'); p(d,'The project uses flight-level departure-delay records. The observed Poisson variance-to-mean ratio is 126.739, so the Poisson calculation is a benchmark rather than evidence of a good fit. Mitsokapas et al. (2021) also report broad delay behavior and emphasize that delay distributions need empirical characterization.')
references(d); d.save(OUT/'Project 1 Lit Review Revised.docx')

d=base('Journal Article Summary Flight Delay Statistics')
p(d,'Selected peer-reviewed journal article: Mitsokapas, Schäfer, Harris, and Beck (2021), Statistical characterization of airplane delays, Scientific Reports, 11, 7855.')
h(d,'Purpose and Method'); p(d,'The authors statistically characterized arrival delays at UK airports from 2018 through 2020. They compared delay behavior across airlines and airports, considered extreme events, and examined changes during the COVID-19 period.')
h(d,'Results and Connection'); p(d,'The article reports broad delay behavior and argues that observed delay distributions can reflect a superposition of simpler distributions. This supports the project conclusion that the empirical daily delayed-flight variance greatly exceeds the Poisson variance. The paper does not validate a Poisson fit for this project’s U.S. departure-delay sample.')
h(d,'Background Conference Paper'); p(d,'Mueller and Chatterji (2002) remains useful background because it compares delay-distribution fits at ten major U.S. airports. It is an AIAA technical-forum conference paper, not the peer-reviewed journal article required for this component.')
references(d); d.save(OUT/'Project 1 Journal Article Revised.docx')

d=base('Flight Delay Analysis Revised Results')
p(d,'This revised results summary reports values generated by the reproducible flight-level analysis, not the monthly arrival-delay aggregate pathway.')
h(d,'Data and Cleaning'); p(d,'The input had 3,000,000 flight records. After excluding records with missing FL_DATE or DEP_DELAY, 2,922,356 records remained. The observed calendar contains 1,704 dates from 2019-01-01 through 2023-08-31. A delayed flight has DEP_DELAY > 0 minutes.')
h(d,'Empirical Results'); p(d,'Departure-delay mean = 10.123 minutes; empirical SD = 49.252 minutes; delayed flights = 992,843 (33.974%). Daily delayed-flight count mean = 582.654 and variance = 73,845.030. The variance-to-mean ratio is 126.739, indicating substantial overdispersion.')
h(d,'Revised Model Definitions'); p(d,'Binomial success is a day with a delayed-flight rate above 40%, giving p = 0.275235. Geometric success is a day on which at least 10% of observed flights have DEP_DELAY > 30 minutes, giving p = 0.487676. These definitions avoid the earlier degenerate p=1 outcomes.')
h(d,'Simulation Evidence');
t=d.add_table(rows=1, cols=3); t.style='Light Shading Accent 1'; hdr=t.rows[0].cells; hdr[0].text='Distribution'; hdr[1].text='Theoretical mean'; hdr[2].text='Simulated mean'
for row in [('Poisson','582.654','582.747'),('Binomial','2.752','2.756'),('Geometric','2.051','2.061'),('Negative Binomial','14.717','14.748'),('Hypergeometric','33.974','33.932')]:
 c=t.add_row().cells
 for i,x in enumerate(row): c[i].text=x
p(d,'All simulations use 10,000 draws and seed 562. Full output and plots are saved under output/results and output/figures.')
references(d); d.save(OUT/'Project 1 Report Revised.docx')
