from docx import Document
from docx.shared import Inches
from pathlib import Path
out=Path('communication_redo_full'); out.mkdir(exist_ok=True)
refs=['Blitzstein, J. K., & Hwang, J. (2019). Introduction to Probability (2nd ed.). Chapman and Hall/CRC.','Mitsokapas, E., Schäfer, B., Harris, R. J., & Beck, C. (2021). Statistical characterization of airplane delays. Scientific Reports, 11, 7855. https://doi.org/10.1038/s41598-021-87279-8','Mueller, E. R., & Chatterji, G. B. (2002). Analysis of aircraft arrival and departure delay characteristics. AIAA Aircraft Technology, Integration, and Operations Technical Forum, AIAA 2002-5866. https://doi.org/10.2514/6.2002-5866']
def doc(title):
 d=Document(); d.sections[0].top_margin=Inches(.75); d.sections[0].bottom_margin=Inches(.75); d.add_heading(title,0); return d
def add(d,h,body): d.add_heading(h,1); [d.add_paragraph(x) for x in body]
def ref(d):
 d.add_heading('References',1); [d.add_paragraph(x) for x in refs]

d=doc('STAT 562 Project 1 Flight Delay Analysis')
add(d,'Introduction',['This project applies five discrete probability distributions to flight-delay data: Poisson, Binomial, Geometric, Negative Binomial, and Hypergeometric. The purpose is to connect distribution theory with observed flight-level departure-delay events and to compare theoretical results with simulation output.','The analysis uses the corrected flight-level pathway. It does not use airport-carrier-month arrival aggregates to make daily departure-delay claims.'])
add(d,'Dataset and Data Preparation',['The input file contained 3,000,000 flight records with FL_DATE and DEP_DELAY. The data-cleaning script retained 2,922,356 records after excluding records with missing flight date or departure delay. The resulting calendar has 1,704 observed dates from 2019-01-01 through 2023-08-31, and every calendar day in that interval is represented.','A delayed flight is defined as DEP_DELAY > 0 minutes. There are 992,843 delayed flights, or 33.974% of cleaned records. The analysis records this provenance in output/tables/preprocessing_summary.csv.'])
add(d,'Descriptive Statistics',['The mean departure delay is 10.123 minutes and the empirical standard deviation is 49.252 minutes. The mean daily delayed-flight count is 582.654, while the empirical daily-count variance is 73,845.030. The empirical variance is far larger than the Poisson variance of 582.654, giving a variance-to-mean ratio of 126.739. This is substantial overdispersion.'])
for title,body in [('Poisson Distribution',['Let X be the number of delayed flights per observed day. X is modeled as Poisson(lambda), with lambda estimated as 582.654. The PMF is P(X=x)=exp(-lambda)lambda^x/x!, E[X]=Var(X)=lambda, and M_X(t)=exp{lambda(exp(t)-1)} for every real t. The 10,000-draw simulation mean is 582.747 and variance is 583.783. The simulation verifies the model calculation, but the observed overdispersion limits Poisson fit.']),('Binomial Distribution',['A Binomial success is a day whose delayed-flight rate exceeds 40%. For a 10-day period, p=0.275235, E[X]=2.752, and Var(X)=1.995. The PMF is choose(n,x)p^x(1-p)^(n-x), and M_X(t)=(1-p+p exp(t))^n for every real t. The simulation mean is 2.756 and variance is 1.989.']),('Geometric Distribution',['A Geometric success is a high-severity day: at least 10% of the day’s observed flights have DEP_DELAY > 30 minutes. This corrected definition avoids the earlier degenerate event defined as any major delay in a large daily sample. With p=0.487676, E[X]=2.051 days and Var(X)=2.154. Under the trials-until-first-success convention, M_X(t)=p exp(t)/[1-(1-p)exp(t)] for t < -log(1-p). The simulation mean is 2.061 and variance is 2.165.']),('Negative Binomial Distribution',['Let X be flights required to observe r=5 delayed flights. With p=0.339741, E[X]=14.717 and Var(X)=28.602. The MGF is [p exp(t)/(1-(1-p)exp(t))]^r for t < -log(1-p). The simulation mean is 14.748 and variance is 28.426.']),('Hypergeometric Distribution',['For sampling without replacement, N=2,922,356, K=992,843, and n=100. E[X]=33.974 and Var(X)=22.431. Its MGF is the finite sum of exp(tx)P(X=x) over valid x and is defined for every real t. The simulation mean is 33.932 and variance is 22.539.'])]: add(d,title,body)
add(d,'Conclusion',['The five distributions describe distinct random experiments. The simulations agree with their theoretical moments. The empirical daily flight-delay counts, however, are much more variable than a Poisson model assumes. The results therefore demonstrate both correct distribution calculations and the importance of checking assumptions against observed data.'])
ref(d); d.save(out/'Project 1 Report Full Revised.docx')

d=doc('Literature Review Discrete Probability Distributions')
add(d,'Introduction',['Discrete distributions model countable outcomes. This review summarizes their applications, assumptions, formulas, and MGF domains. The theoretical formulas follow Blitzstein and Hwang (2019).'])
for title,body in [('Poisson Distribution',['The Poisson distribution models event counts in a fixed interval under independent events and a constant rate lambda. Its PMF is exp(-lambda)lambda^x/x!, its mean and variance equal lambda, and M_X(t)=exp{lambda(exp(t)-1)} for t in R. It is useful for counts such as customer arrivals and daily flight-delay events, but correlated weather and congestion can violate independence.']),('Binomial Distribution',['The Binomial distribution counts successes in n independent Bernoulli trials with common probability p. Its PMF is choose(n,x)p^x(1-p)^(n-x), mean np, variance np(1-p), and MGF (1-p+p exp(t))^n for t in R. It applies to fixed observation periods and requires binary outcomes, common p, and independence.']),('Geometric Distribution',['The Geometric distribution gives trials until the first success. Under the project convention its PMF is (1-p)^(x-1)p, mean 1/p, variance (1-p)/p^2, and MGF p exp(t)/[1-(1-p)exp(t)] for t < -log(1-p). It is memoryless and requires independent trials with common p.']),('Negative Binomial Distribution',['The Negative Binomial distribution extends the Geometric distribution to r successes. Its mean is r/p, variance r(1-p)/p^2, and MGF [p exp(t)/(1-(1-p)exp(t))]^r for t < -log(1-p).']),('Hypergeometric Distribution',['The Hypergeometric distribution counts successes in a finite sample without replacement. Its mean is nK/N and its variance includes the finite-population correction. Its MGF is the finite support sum of exp(tx)P(X=x), defined for t in R. Sampling without replacement distinguishes it from the Binomial model.'])]: add(d,title,body)
add(d,'Flight Delay Context',['Mitsokapas et al. (2021) show that observed delay distributions can be broad and affected by context. This reinforces the project finding that empirical daily counts are overdispersed relative to Poisson expectations. Mueller and Chatterji (2002) remains useful aviation background but is an AIAA technical-forum paper rather than the peer-reviewed journal source.'])
ref(d); d.save(out/'Project 1 Lit Review Full Revised.docx')

d=doc('Journal Article Analysis Flight Delay Statistics')
add(d,'Selected Peer Reviewed Article',['Mitsokapas, Schäfer, Harris, and Beck (2021), Statistical characterization of airplane delays, published in Scientific Reports, is the required journal article.'])
add(d,'Purpose and Methodology',['The authors analyzed arrival-delay behavior at UK airports between 2018 and 2020. They compared mean delay and extreme events across airlines and airports, including changes during the COVID-19 period. Their statistical characterization addresses how to summarize heterogeneous delay behavior.'])
add(d,'Results and Connection',['The article reports broad delay behavior and describes delay distributions as a superposition of simple distributions. This connects directly to the project’s daily-count variance-to-mean ratio of 126.739. The project therefore treats its Poisson calculation as a theoretical benchmark rather than a proof of empirical fit.'])
add(d,'Background Conference Paper',['Mueller and Chatterji (2002) is retained as background because it compared delay-distribution fits at ten U.S. airports. It is correctly identified as an AIAA Aircraft Technology, Integration, and Operations Technical Forum paper. It does not replace the peer-reviewed journal article above.'])
ref(d); d.save(out/'Project 1 Journal Article Full Revised.docx')
